### PR TITLE
Basic component setup

### PR DESCRIPTION
**Pull request by AndrewPomo**

### CODE REVIEW

**Comment by AndrewPomo** [comment]
@leadervle can I get a quick look? nothing fancy here.

**Comment by leadervle** [comment]
I can take a look.

**Review by leadervle — APPROVED** [review]
Looks solid, nice template to start working off of. I don't see any sort of errors or problems currently.  I'm guessing the format that the Airbnb website has for its separate parts is structured in the same format?

**Comment by AndrewPomo** [comment]
yessir @leadervle

**Pull request merged**
