### PR TITLE
complete initial file structure and server doc

### PR DESCRIPTION
**Pull request by AndrewPomo**

### CODE REVIEW

**Comment by AndrewPomo** [comment]
@albullington can you take a look at this?

**Review by albullington — COMMENTED** [review]
@AndrewPomo looks good. It looks like SERIAL auto-increments the table IDs? A few thoughts: 

- Hack Reactor has a special config for Eslint, so you might not need all of those dependencies. 

- Should user_id in the reviews table be an INT? 

- Double check your module.exports in server.js. It looks like you're setting module.exports equal to a function, which could lead to errors since module.exports is an object.

**Comment by AndrewPomo** [comment]
Wow great catch on the `user-id`.
Also updating the exports in the server. Thanks @albullington!

**Comment by AndrewPomo** [comment]
@albullington if these changes look adequate give me a thumbs up :]

**Pull request merged**
